const weighting = {
    "0": { "even": 0, "odd": 1 },
    "A": { "even": 0, "odd": 1 },
    "1": { "even": 1, "odd": 0 },
    "B": { "even": 1, "odd": 0 },
    "2": { "even": 2, "odd": 5 },
    "C": { "even": 2, "odd": 5 },
    "3": { "even": 3, "odd": 7 },
    "D": { "even": 3, "odd": 7 },
    "4": { "even": 4, "odd": 9 },
    "E": { "even": 4, "odd": 9 },
    "5": { "even": 5, "odd": 13 },
    "F": { "even": 5, "odd": 13 },
    "6": { "even": 6, "odd": 15 },
    "G": { "even": 6, "odd": 15 },
    "7": { "even": 7, "odd": 17 },
    "H": { "even": 7, "odd": 17 },
    "8": { "even": 8, "odd": 19 },
    "I": { "even": 8, "odd": 19 },
    "9": { "even": 9, "odd": 21 },
    "J": { "even": 9, "odd": 21 },
    "K": { "even": 10, "odd": 2 },
    "L": { "even": 11, "odd": 4 },
    "M": { "even": 12, "odd": 18 },
    "N": { "even": 13, "odd": 20 },
    "O": { "even": 14, "odd": 11 },
    "P": { "even": 15, "odd": 3 },
    "Q": { "even": 16, "odd": 6 },
    "R": { "even": 17, "odd": 8 },
    "S": { "even": 18, "odd": 12 },
    "T": { "even": 19, "odd": 14 },
    "U": { "even": 20, "odd": 16 },
    "V": { "even": 21, "odd": 10 },
    "W": { "even": 22, "odd": 22 },
    "X": { "even": 23, "odd": 23 },
    "Y": { "even": 24, "odd": 24 },
    "Z": { "even": 25, "odd": 25 }
}

export default weighting